"""Add AI fields to TrackedProduct

Revision ID: fe358f44541a
Revises: 9e570c8725cb
Create Date: 2026-05-31 17:42:03.282135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe358f44541a'
down_revision = '9e570c8725cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracked_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rating_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('brand', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('specs_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_extracted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracked_product', schema=None) as batch_op:
        batch_op.drop_column('ai_extracted')
        batch_op.drop_column('specs_json')
        batch_op.drop_column('category')
        batch_op.drop_column('brand')
        batch_op.drop_column('rating_count')
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
